vich_uploader:
    db_driver: orm

    mappings:
        commercial_image:
            uri_prefix: /images/direction_commerciale/commercials
            upload_destination: '%kernel.project_dir%/public/images/direction_commerciale/commercials'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        prospect_image:
            uri_prefix: /images/direction_commerciale/prospect
            upload_destination: '%kernel.project_dir%/public/images/direction_commerciale/prospect'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
